### ISSUE TITLE
Exception on Windows Opening Collection With Special Characters

### ISSUE THREAD

**Issue by gha88** [appknox/postmanparser#20]
On Windows OS default encoding isn't UTF-8 and another encoding is used.
In case of 2 bytes characters (Chinese for example) the open file failed.

**Comment by subho007** [comment]
@kirankumbhar do you want to take a look at this ?

**Comment by subho007** [comment]
Thanks for the contribution !

**Comment by kirankumbhar** [comment]
@subho007 Missed this notification.
